export const eventsWinnersData = [
  {
    id: "1",
    title: "Zwycięzcy World Bachata Masters 2024",
    description: "Zobacz mistrzowskie pary z największego konkursu bachaty",
    image: "/images/world-bachata-masters.jpg",
    url: "world-bachata-masters",
  },
  {
    id: "2",
    title: "Polacy na podium European Bachata Cup",
    description: "Sukces naszych tancerzy w międzynarodowym turnieju",
    image: "/images/european-bachata-cup.jpg",
    url: "european-bachata-cup",
  },
  {
    id: "3",
    title: "Gwiazdy Bachata Stars Festival",
    description: "Najlepsze występy i zwycięzcy konkursu",
    image: "/images/bachata-stars-festival.jpg",
    url: "bachata-stars-festival",
  },
  {
    id: "4",
    title: "TOP 10 Par Bachaty w Polsce",
    description: "Ranking najlepszych tancerzy 2024",
    image: "/images/top-polish-dancers.jpg",
    url: "top-polish-dancers",
  },
  {
    id: "5",
    title: "Mistrzowie Sensual Bachata Show",
    description: "Zwycięskie choreografie i najlepsze momenty",
    image: "/images/sensual-bachata-show.jpg",
    url: "sensual-bachata-show",
  },
  {
    id: "6",
    title: "Debiutanci roku w bachacie",
    description: "Nowe talenty, które warto obserwować",
    image: "/images/new-talents.jpg",
    url: "new-talents",
  },
  {
    id: "7",
    title: "Laureaci Dominican Bachata Contest",
    description: "Relacja z konkursu w stylu dominikańskim",
    image: "/images/dominican-contest.jpg",
    url: "dominican-contest",
  },
];
