import { BachataVideoItem } from "./types";

export const bachataVideosData: BachataVideoItem[] = [
  {
    id: "2",
    title: "Luis & Andrea",
    youtubeId: "wW6gqp8hEkE",
    url: "LuisyAndrea Official",
    channelTitle: "LuisyAndrea Official",
    subscriberCount: "102,5 tys. subskrybentów",
    channelImage: "/images/channels/luis-andrea.jpg",
  },
  {
    id: "3",
    title: "Gero & Migue",
    youtubeId: "upJYK94rJKI",
    url: "Gero & Migue",
    channelTitle: "Gero & Migue",
    subscriberCount: "156,7 tys. subskrybentów",
    channelImage: "/images/channels/gero-migue.jpg",
  },
  {
    id: "4",
    title: "Korke & Judith",
    youtubeId: "Cc52p07wuDE",
    url: "Korke & Judith",
    channelTitle: "Korke & Judith",
    subscriberCount: "5,8 tys. subskrybentów",
    channelImage: "/images/channels/korke-judith.jpg",
  },
  {
    id: "1",
    title: "KLAU Y ROS",
    youtubeId: "dQDeLHI8r08",
    url: "KLAU Y ROS",
    channelTitle: "KLAU Y ROS",
    subscriberCount: "89,2 tys. subskrybentów",
    channelImage: "/images/channels/klau-ros.jpg",
  },

  {
    id: "6",
    title: "Ataca y La Alemana",
    youtubeId: "eAWIuRvYjAg",
    url: "Ataca y La Alemana",
    channelTitle: "Ataca y La Alemana",
    subscriberCount: "892,1 tys. subskrybentów",
    channelImage: "/images/channels/ataca-alemana.jpg",
  },
  {
    id: "7",
    title: "Marco & Sara",
    youtubeId: "idk6516lEts",
    url: "Marco & Sara",
    channelTitle: "Marco & Sara",
    subscriberCount: "167,8 tys. subskrybentów",
    channelImage: "/images/channels/marco-sara.jpg",
  },
  {
    id: "8",
    title: "Daniel & Desiree",
    youtubeId: "rkDUJ-Pom8U",
    url: "Daniel & Desiree",
    channelTitle: "Daniel & Desiree",
    subscriberCount: "892,1 tys. subskrybentów",
    channelImage: "/images/channels/daniel-desiree.jpg",
  },
  {
    id: "5",
    title: "Cristian & Gabriella",
    youtubeId: "ZSSXSi1rO24",
    url: "Cristian & Gabriella",
    channelTitle: "Cristian & Gabriella",
    subscriberCount: "12,3 tys. subskrybentów",
    channelImage: "/images/channels/cristian-gabriella.jpg",
  },

  {
    id: "9",
    title: "Cornel & Rithika",
    youtubeId: "4INmV6CzPFc",
    url: "Cornel & Rithika",
    channelTitle: "Cornel & Rithika",
    subscriberCount: "78,3 tys. subskrybentów",
    channelImage: "/images/channels/Cornel & Rithika.jpg",
  },
  {
    id: "10",
    title: "Janis & Zoé",
    youtubeId: "Gx-o5iQP2KU",
    url: "Janis & Zoé",
    channelTitle: "Janis & Zoé",
    subscriberCount: "45,6 tys. subskrybentów",
    channelImage: "/images/channels/janis-zoe.jpg",
  },
  {
    id: "11",
    title: "Kike & Nahir",
    youtubeId: "E43-JJnXB0Q",
    url: "Kike & Nahir",
    channelTitle: "Kike & Nahir",
    subscriberCount: "134,2 tys. subskrybentów",
    channelImage: "/images/channels/kike-nahir.jpg",
  },
  {
    id: "12",
    title: "Daniel & Carla",
    youtubeId: "L3kDG1VU4PE",
    url: "Daniel & Carla",
    channelTitle: "Daniel & Carla",
    subscriberCount: "89,7 tys. subskrybentów",
    channelImage: "/images/channels/daniel-carla.jpg",
  },
  {
    id: "13",
    title: "Sergio & Sofia",
    youtubeId: "QN8BQ7DXTJ4",
    url: "Sergio & Sofia",
    channelTitle: "Sergio & Sofia",
    subscriberCount: "167,4 tys. subskrybentów",
    channelImage: "/images/channels/sergio-sofia.jpg",
  },
  {
    id: "14",
    title: "Juan & Katherine",
    youtubeId: "H2YbL7ErHKs",
    url: "Juan & Katherine",
    channelTitle: "Juan & Katherine",
    subscriberCount: "92,8 tys. subskrybentów",
    channelImage: "/images/channels/juan-katherine.jpg",
  },
  {
    id: "15",
    title: "Carlos & Fernanda",
    youtubeId: "K9XZHjfY_MA",
    url: "Carlos & Fernanda",
    channelTitle: "Carlos & Fernanda",
    subscriberCount: "145,3 tys. subskrybentów",
    channelImage: "/images/channels/carlos-fernanda.jpg",
  },
  {
    id: "16",
    title: "David & Kim",
    youtubeId: "R4YZ8QcRqWE",
    url: "David & Kim",
    channelTitle: "David & Kim",
    subscriberCount: "78,9 tys. subskrybentów",
    channelImage: "/images/channels/david-kim.jpg",
  },
  {
    id: "17",
    title: "Felipe & Laura",
    youtubeId: "X9YZ8B2K4WY",
    url: "Felipe & Laura",
    channelTitle: "Felipe & Laura",
    subscriberCount: "112,6 tys. subskrybentów",
    channelImage: "/images/channels/felipe-laura.jpg",
  },
  {
    id: "18",
    title: "Jorge & Tanja",
    youtubeId: "M7N2K8P4L6Q",
    url: "Jorge & Tanja",
    channelTitle: "Jorge & Tanja",
    subscriberCount: "167,2 tys. subskrybentów",
    channelImage: "/images/channels/jorge-tanja.jpg",
  },
  {
    id: "19",
    title: "Manuel & Maria",
    youtubeId: "P9Q7R4K8L2M",
    url: "Manuel & Maria",
    channelTitle: "Manuel & Maria",
    subscriberCount: "98,4 tys. subskrybentów",
    channelImage: "/images/channels/manuel-maria.jpg",
  },
  {
    id: "20",
    title: "Pedro & Giusy",
    youtubeId: "T8K9L2M4N6P",
    url: "Pedro & Giusy",
    channelTitle: "Pedro & Giusy",
    subscriberCount: "145,7 tys. subskrybentów",
    channelImage: "/images/channels/pedro-giusy.jpg",
  },
];
