export const fashionGridData = [
  {
    id: "1",
    title: "Sukienki do tańca - Nowa kolekcja 2024",
    description: "Eleganckie sukienki idealne do bachaty i salsy",
    image: "/images/dance-dress-collection.jpg",
    url: "dance-dresses",
  },
  {
    id: "2",
    title: "Buty taneczne - Jak wybrać idealne?",
    description: "Przewodnik po butach do tańca",
    image: "/images/dance-shoes-guide.jpg",
    url: "dance-shoes",
  },
  {
    id: "3",
    title: "Trendy w modzie tanecznej na 2024",
    description: "Co będzie modne w tym sezonie?",
    image: "/images/dance-fashion-trends.jpg",
    url: "fashion-trends",
  },
  {
    id: "4",
    title: "Spódnice do tańca - Nowa dostawa",
    description: "Lekkie i zwiewne spódnice do bachaty",
    image: "/images/dance-skirts.jpg",
    url: "dance-skirts",
  },
  {
    id: "5",
    title: "Akcesoria taneczne - Must have",
    description: "Dodatki, które musisz mieć",
    image: "/images/dance-accessories.jpg",
    url: "dance-accessories",
  },
  {
    id: "6",
    title: "Makijaż sceniczny - Porady ekspertów",
    description: "Jak wykonać trwały makijaż na występy",
    image: "/images/stage-makeup.jpg",
    url: "stage-makeup",
  },
  {
    id: "7",
    title: "Fryzury do tańca - Najnowsze trendy",
    description: "Modne upięcia na parkiet",
    image: "/images/dance-hairstyles.jpg",
    url: "dance-hairstyles",
  },
  {
    id: "8",
    title: "Biżuteria taneczna - Błyszcz na parkiecie",
    description: "Najnowsza kolekcja biżuterii do tańca",
    image: "/images/dance-jewelry.jpg",
    url: "dance-jewelry",
  },
  {
    id: "9",
    title: "Stroje męskie do bachaty",
    description: "Elegancja i wygoda dla panów",
    image: "/images/mens-dance-fashion.jpg",
    url: "mens-fashion",
  },
  {
    id: "10",
    title: "Rajstopy i pończochy taneczne",
    description: "Przegląd najlepszych marek",
    image: "/images/dance-tights.jpg",
    url: "dance-tights",
  },
];
